version: '3.8'

services:
  accessibista:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: accessibista-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - accessibista-network

networks:
  accessibista-network:
    driver: bridge
